XCOMMONS-2596: ObservationManager#notify does not protect against things like NoClassDefFoundError
(cherry picked from commit ea8e0e72138e13c66253ddc2e81dd6162cf1ec2f)