Improve exception message when failing to initialize a component because a class could not be found. Now we now which component class is being loaded in the exception message whereas before we only had a NoClassDefFoundError on the ancillary class that was trying to be loaded.